export const CONNECTION: string = "connection";

export const ENVOYER_MESSAGE_BMPDIFF: string = "ENVOYER_MESSAGE_BMPDIFF";
export const ENVOYER_MESSAGE_NOM_PRIS: string = "ENVOYER_MESSAGE_NOM_PRIS";

export const ENVOYER_PARTIE_SIMPLE_ATTENTE: string = "ENVOYER_PARTIE_SIMPLE_ATTENTE";
export const ENVOYER_PARTIE_MULTIPLE_ATTENTE: string = "ENVOYER_PARTIE_MULTIPLE_ATTENTE";

export const DELETE_PARTIE_SIMPLE_ATTENTE: string = "DELETE_PARTIE_SIMPLE_ATTENTE";
export const DELETE_PARTIE_MULTIPLE_ATTENTE: string = "DELETE_PARTIE_MULTIPLE_ATTENTE";

export const ENVOYER_PARTIE_MULTIPLE: string = "ENVOYER_PARTIE_MULTIPLE";
export const ENVOYER_PARTIE_SIMPLE: string = "ENVOYER_PARTIE_SIMPLE";

export const DELETE_PARTIE_SIMPLE: string = "DELETE_PARTIE_SIMPLE";
export const DELETE_PARTIE_MULTIPLE: string = "DELETE_PARTIE_MULTIPLE";

export const DIALOG_ATTENTE_MULTIPLE_FERME: string = "DIALOG_ATTENTE_MULTIPLE_FERME";
export const DIALOG_ATTENTE_SIMPLE_FERME: string = "DIALOG_ATTENTE_SIMPLE_FERME";

export const JOINDRE_PARTIE_MULTIJOUEUR_SIMPLE: string = "JOINDRE_PARTIE_MULTIJOUER_SIMPLE";
export const JOINDRE_PARTIE_MULTIJOUEUR_MULTIPLE: string = "JOINDRE_PARTIE_MULTIJOUER_MULTIPLE";

export const DIFFERENCE_TROUVEE_MULTIJOUEUR_SIMPLE: string = "DIFFERENCE_TROUVEE_MULTIJOUEUR_SIMPLE";
export const DIFFERENCE_TROUVEE_MULTIJOUEUR_MULTIPLE: string = "DIFFERENCE_TROUVEE_MULTIJOUEUR_MULTIPLE";

export const PARTIE_SIMPLE_MULTIJOUEUR_TERMINEE: string = "PARTIE_SIMPLE_MULTIJOUEUR_TERMINEE";
export const PARTIE_MULTIPLE_MULTIJOUEUR_TERMINEE: string = "PARTIE_MULTIPLE_MULTIJOUEUR_TERMINEE";

export const ERREUR_PARTIE_SIMPLE: string = "ERREUR_PARTIE_SIMPLE";
export const ERREUR_PARTIE_MULTIPLE: string = "ERREUR_PARTIE_MULTIPLE";

export const PARTIES_SIMPLES_CHARGEES: string = "PARTIES_SIMPLES_CHARGEES";
export const PARTIES_MULTIPLES_CHARGEES: string = "PARTIES_MULTIPLES_CHARGEES";

export const CONNECTION_USER: string = "CONNECTION_USER";
export const DECONNECTION_USER: string = "DECONNECTION_USER";
export const MEILLEUR_TEMPS: string = "MEILLEUR_TEMPS";