export const CONNECTION: string = "connection";
export const ENVOYER_MESSAGE_BMPDIFF: string = "ENVOYER_MESSAGE_BMPDIFF";
export const ENVOYER_MESSAGE_NOM_PRIS: string = "ENVOYER_MESSAGE_NOM_PRIS";
export const ENVOYER_PARTIE_SIMPLE: string = "ENVOYER_PARTIE_SIMPLE";
export const ENVOYER_PARTIE_SIMPLE_ATTENTE: string = "ENVOYER_PARTIE_SIMPLE_ATTENTE";
export const DELETE_PARTIE_SIMPLE_ATTENTE: string = "DELETE_PARTIE_SIMPLE_ATTENTE";